insert into frame (model, frameType, brand) values ('929', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('Grand Vitara', 'metàlica', 'Suzuki');
insert into frame (model, frameType, brand) values ('TSX', 'pasta', 'Acura');
insert into frame (model, frameType, brand) values ('Outlander', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('xA', 'flotant', 'Scion');
insert into frame (model, frameType, brand) values ('A3', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('9-7X', 'metàlica', 'Saab');
insert into frame (model, frameType, brand) values ('F350', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Legacy', 'metàlica', 'Subaru');
insert into frame (model, frameType, brand) values ('CL-Class', 'flotant', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Continental', 'pasta', 'Bentley');
insert into frame (model, frameType, brand) values ('Corolla', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Impreza', 'flotant', 'Subaru');
insert into frame (model, frameType, brand) values ('Montero Sport', 'metàlica', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Accord', 'pasta', 'Honda');
insert into frame (model, frameType, brand) values ('Grand Caravan', 'flotant', 'Dodge');
insert into frame (model, frameType, brand) values ('PT Cruiser', 'flotant', 'Chrysler');
insert into frame (model, frameType, brand) values ('Sundance', 'metàlica', 'Plymouth');
insert into frame (model, frameType, brand) values ('Tundra', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Coupe', 'pasta', 'Maserati');
insert into frame (model, frameType, brand) values ('3000GT', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('CL', 'flotant', 'Acura');
insert into frame (model, frameType, brand) values ('Dakota Club', 'flotant', 'Dodge');
insert into frame (model, frameType, brand) values ('Corvair 500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('I', 'flotant', 'Infiniti');
insert into frame (model, frameType, brand) values ('Rabbit', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Aura', 'flotant', 'Saturn');
insert into frame (model, frameType, brand) values ('Avalon', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Civic Si', 'pasta', 'Honda');
insert into frame (model, frameType, brand) values ('Camry', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Range Rover', 'metàlica', 'Land Rover');
insert into frame (model, frameType, brand) values ('MKX', 'flotant', 'Lincoln');
insert into frame (model, frameType, brand) values ('530', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('599 GTB Fiorano', 'pasta', 'Ferrari');
insert into frame (model, frameType, brand) values ('164', 'flotant', 'Alfa Romeo');
insert into frame (model, frameType, brand) values ('1 Series', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Sonata', 'metàlica', 'Hyundai');
insert into frame (model, frameType, brand) values ('Rodeo', 'flotant', 'Isuzu');
insert into frame (model, frameType, brand) values ('Venza', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Grand Vitara', 'pasta', 'Suzuki');
insert into frame (model, frameType, brand) values ('Forenza', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('Jetta', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Gallardo', 'flotant', 'Lamborghini');
insert into frame (model, frameType, brand) values ('riolet', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Sonata', 'flotant', 'Hyundai');
insert into frame (model, frameType, brand) values ('S10', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Intrepid', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('Breeze', 'flotant', 'Plymouth');
insert into frame (model, frameType, brand) values ('Quest', 'metàlica', 'Nissan');
insert into frame (model, frameType, brand) values ('Tribute', 'metàlica', 'Mazda');
insert into frame (model, frameType, brand) values ('Bonneville', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Grand Marquis', 'pasta', 'Mercury');
insert into frame (model, frameType, brand) values ('Sienna', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Escape', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Grand Am', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Falcon', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('DBS', 'pasta', 'Aston Martin');
insert into frame (model, frameType, brand) values ('62', 'metàlica', 'Maybach');
insert into frame (model, frameType, brand) values ('Celica', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Grand Marquis', 'pasta', 'Mercury');
insert into frame (model, frameType, brand) values ('Mustang', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Taurus', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Cavalier', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Civic', 'metàlica', 'Honda');
insert into frame (model, frameType, brand) values ('Q', 'pasta', 'Infiniti');
insert into frame (model, frameType, brand) values ('X6', 'flotant', 'BMW');
insert into frame (model, frameType, brand) values ('GTO', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Pathfinder', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('XJ Series', 'pasta', 'Jaguar');
insert into frame (model, frameType, brand) values ('Rockette', 'pasta', 'Fairthorpe');
insert into frame (model, frameType, brand) values ('Expedition', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Pathfinder', 'metàlica', 'Nissan');
insert into frame (model, frameType, brand) values ('Durango', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('Liberty', 'metàlica', 'Jeep');
insert into frame (model, frameType, brand) values ('Suburban 2500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Yaris', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Skylark', 'flotant', 'Buick');
insert into frame (model, frameType, brand) values ('Sierra 1500', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('Corvette', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Samurai', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('200SX', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('Crown Victoria', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Q5', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('E-Class', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Turbo Firefly', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Sebring', 'metàlica', 'Chrysler');
insert into frame (model, frameType, brand) values ('Pathfinder', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('Sebring', 'pasta', 'Chrysler');
insert into frame (model, frameType, brand) values ('Silverado 2500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Celica', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('62', 'flotant', 'Maybach');
insert into frame (model, frameType, brand) values ('Caravan', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('Cube', 'flotant', 'Nissan');
insert into frame (model, frameType, brand) values ('968', 'pasta', 'Porsche');
insert into frame (model, frameType, brand) values ('E-Class', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('300E', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Q7', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Grand Vitara', 'pasta', 'Suzuki');
insert into frame (model, frameType, brand) values ('Matrix', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('300SD', 'pasta', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Ram Van 2500', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('Accord Crosstour', 'pasta', 'Honda');
insert into frame (model, frameType, brand) values ('Enclave', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('Escalade', 'pasta', 'Cadillac');
insert into frame (model, frameType, brand) values ('850', 'metàlica', 'Volvo');
insert into frame (model, frameType, brand) values ('Truck Xtracab SR5', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('944', 'metàlica', 'Porsche');
insert into frame (model, frameType, brand) values ('Journey', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('Titan', 'metàlica', 'Nissan');
insert into frame (model, frameType, brand) values ('Grand Vitara', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('Mighty Max', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('E250', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Sonoma Club Coupe', 'metàlica', 'GMC');
insert into frame (model, frameType, brand) values ('Grand Cherokee', 'metàlica', 'Jeep');
insert into frame (model, frameType, brand) values ('Impreza', 'metàlica', 'Subaru');
insert into frame (model, frameType, brand) values ('Santa Fe', 'flotant', 'Hyundai');
insert into frame (model, frameType, brand) values ('Phantom', 'metàlica', 'Rolls-Royce');
insert into frame (model, frameType, brand) values ('Z3', 'flotant', 'BMW');
insert into frame (model, frameType, brand) values ('Element', 'metàlica', 'Honda');
insert into frame (model, frameType, brand) values ('Reno', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('Camry', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Safari', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('Excel', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('V70', 'pasta', 'Volvo');
insert into frame (model, frameType, brand) values ('Truck', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Avalon', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Tribute', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('Lumina', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Esteem', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('RX', 'pasta', 'Lexus');
insert into frame (model, frameType, brand) values ('3000GT', 'metàlica', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('S-Class', 'pasta', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Accent', 'metàlica', 'Hyundai');
insert into frame (model, frameType, brand) values ('Econoline E150', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Escalade ESV', 'metàlica', 'Cadillac');
insert into frame (model, frameType, brand) values ('Continental', 'pasta', 'Bentley');
insert into frame (model, frameType, brand) values ('RS4', 'pasta', 'Audi');
insert into frame (model, frameType, brand) values ('Escalade', 'flotant', 'Cadillac');
insert into frame (model, frameType, brand) values ('RSX', 'flotant', 'Acura');
insert into frame (model, frameType, brand) values ('Outlander', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Taurus', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Grand Am', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Ram', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('Firefly', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('88', 'metàlica', 'Oldsmobile');
insert into frame (model, frameType, brand) values ('Fifth Ave', 'flotant', 'Chrysler');
insert into frame (model, frameType, brand) values ('Breeze', 'pasta', 'Plymouth');
insert into frame (model, frameType, brand) values ('QX56', 'metàlica', 'Infiniti');
insert into frame (model, frameType, brand) values ('Escape', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Vibe', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('F350', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('RX', 'pasta', 'Lexus');
insert into frame (model, frameType, brand) values ('G35', 'flotant', 'Infiniti');
insert into frame (model, frameType, brand) values ('Aviator', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('Equinox', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Crown Victoria', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('E-Class', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Camry', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Exige', 'metàlica', 'Lotus');
insert into frame (model, frameType, brand) values ('CX-9', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('Model T', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('D350', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('RS 4', 'pasta', 'Audi');
insert into frame (model, frameType, brand) values ('Integra', 'pasta', 'Acura');
insert into frame (model, frameType, brand) values ('Windstar', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('850', 'pasta', 'Volvo');
insert into frame (model, frameType, brand) values ('Thunderbird', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('A6', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('Quattroporte', 'metàlica', 'Maserati');
insert into frame (model, frameType, brand) values ('A4', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('Grand Prix', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Suburban 2500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Montana SV6', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Impreza', 'metàlica', 'Subaru');
insert into frame (model, frameType, brand) values ('IS', 'pasta', 'Lexus');
insert into frame (model, frameType, brand) values ('Chariot', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Monte Carlo', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Pilot', 'flotant', 'Honda');
insert into frame (model, frameType, brand) values ('Liberty', 'flotant', 'Jeep');
insert into frame (model, frameType, brand) values ('MX-6', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('Prizm', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Prius v', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('2500', 'metàlica', 'Ram');
insert into frame (model, frameType, brand) values ('3 Series', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Vega', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Mazdaspeed6', 'metàlica', 'Mazda');
insert into frame (model, frameType, brand) values ('MKS', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('Passat', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('XL7', 'flotant', 'Suzuki');
insert into frame (model, frameType, brand) values ('Century', 'metàlica', 'Buick');
insert into frame (model, frameType, brand) values ('Excel', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Firefly', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('H1', 'pasta', 'Hummer');
insert into frame (model, frameType, brand) values ('Avalanche 2500', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Colorado', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('GX', 'flotant', 'Lexus');
insert into frame (model, frameType, brand) values ('Cougar', 'flotant', 'Mercury');
insert into frame (model, frameType, brand) values ('Lancer', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('E-Series', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Mazda6', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('4Runner', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Rio', 'flotant', 'Kia');
insert into frame (model, frameType, brand) values ('S10', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Solara', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Z8', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Allroad', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Montana', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Typ-1', 'flotant', 'Aptera');
insert into frame (model, frameType, brand) values ('62', 'metàlica', 'Maybach');
insert into frame (model, frameType, brand) values ('Amanti', 'pasta', 'Kia');
insert into frame (model, frameType, brand) values ('GX', 'flotant', 'Lexus');
insert into frame (model, frameType, brand) values ('GS', 'flotant', 'Lexus');
insert into frame (model, frameType, brand) values ('Corrado', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Aspire', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Pathfinder', 'flotant', 'Nissan');
insert into frame (model, frameType, brand) values ('G35', 'metàlica', 'Infiniti');
insert into frame (model, frameType, brand) values ('Passat', 'flotant', 'Volkswagen');
insert into frame (model, frameType, brand) values ('911', 'metàlica', 'Porsche');
insert into frame (model, frameType, brand) values ('Charger', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('626', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('9-3', 'metàlica', 'Saab');
insert into frame (model, frameType, brand) values ('Envoy', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('Comanche', 'metàlica', 'Jeep');
insert into frame (model, frameType, brand) values ('Windstar', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Jetta', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('500SL', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('LaCrosse', 'metàlica', 'Buick');
insert into frame (model, frameType, brand) values ('Park Avenue', 'flotant', 'Buick');
insert into frame (model, frameType, brand) values ('Escape', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Thunderbird', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('SLK-Class', 'flotant', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Tiguan', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Camaro', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('RX-8', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('Mountaineer', 'metàlica', 'Mercury');
insert into frame (model, frameType, brand) values ('riolet', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('Firefly', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('600', 'flotant', 'BMW');
insert into frame (model, frameType, brand) values ('M6', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('Seville', 'pasta', 'Cadillac');
insert into frame (model, frameType, brand) values ('Alliance', 'flotant', 'Renault');
insert into frame (model, frameType, brand) values ('Sonoma', 'metàlica', 'GMC');
insert into frame (model, frameType, brand) values ('Sunfire', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Safari', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('MKT', 'metàlica', 'Lincoln');
insert into frame (model, frameType, brand) values ('Sequoia', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Altima', 'metàlica', 'Nissan');
insert into frame (model, frameType, brand) values ('Lancer Evolution', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Savana', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('LS', 'flotant', 'Lincoln');
insert into frame (model, frameType, brand) values ('S80', 'flotant', 'Volvo');
insert into frame (model, frameType, brand) values ('MKZ', 'flotant', 'Lincoln');
insert into frame (model, frameType, brand) values ('Cube', 'flotant', 'Nissan');
insert into frame (model, frameType, brand) values ('Passat', 'flotant', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Quest', 'flotant', 'Nissan');
insert into frame (model, frameType, brand) values ('Integra', 'pasta', 'Acura');
insert into frame (model, frameType, brand) values ('Sportvan G30', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Trooper', 'metàlica', 'Isuzu');
insert into frame (model, frameType, brand) values ('Rainier', 'flotant', 'Buick');
insert into frame (model, frameType, brand) values ('S4', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Camaro', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Breeze', 'pasta', 'Plymouth');
insert into frame (model, frameType, brand) values ('Camaro', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('VUE', 'pasta', 'Saturn');
insert into frame (model, frameType, brand) values ('F-Series', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('2500', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('240', 'flotant', 'Volvo');
insert into frame (model, frameType, brand) values ('E350', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Savana 1500', 'metàlica', 'GMC');
insert into frame (model, frameType, brand) values ('GTI', 'flotant', 'Volkswagen');
insert into frame (model, frameType, brand) values ('H1', 'metàlica', 'Hummer');
insert into frame (model, frameType, brand) values ('IS F', 'pasta', 'Lexus');
insert into frame (model, frameType, brand) values ('Express 3500', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Brat', 'pasta', 'Subaru');
insert into frame (model, frameType, brand) values ('Accord', 'flotant', 'Honda');
insert into frame (model, frameType, brand) values ('Econoline E250', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Passat', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('F-Series', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Amanti', 'flotant', 'Kia');
insert into frame (model, frameType, brand) values ('GT500', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('XR4Ti', 'pasta', 'Merkur');
insert into frame (model, frameType, brand) values ('LS', 'metàlica', 'Lexus');
insert into frame (model, frameType, brand) values ('90', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('2500', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('MKT', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('90', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('Cabriolet', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('960', 'flotant', 'Volvo');
insert into frame (model, frameType, brand) values ('Camry', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Mariner', 'pasta', 'Mercury');
insert into frame (model, frameType, brand) values ('Navigator', 'metàlica', 'Lincoln');
insert into frame (model, frameType, brand) values ('Econoline E250', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('300ZX', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('Passat', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Metro', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('228', 'metàlica', 'Maserati');
insert into frame (model, frameType, brand) values ('Tribute', 'metàlica', 'Mazda');
insert into frame (model, frameType, brand) values ('CX-5', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('CTS-V', 'flotant', 'Cadillac');
insert into frame (model, frameType, brand) values ('Legend', 'flotant', 'Acura');
insert into frame (model, frameType, brand) values ('Aura', 'pasta', 'Saturn');
insert into frame (model, frameType, brand) values ('Jetta', 'flotant', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Grand Am', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Grand Am', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Montero', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Marquis', 'pasta', 'Mercury');
insert into frame (model, frameType, brand) values ('LX', 'flotant', 'Lexus');
insert into frame (model, frameType, brand) values ('Yukon XL 1500', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('9-3', 'flotant', 'Saab');
insert into frame (model, frameType, brand) values ('Firefly', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Golf', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Z4 M', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('Brooklands', 'metàlica', 'Bentley');
insert into frame (model, frameType, brand) values ('Viper RT/10', 'flotant', 'Dodge');
insert into frame (model, frameType, brand) values ('Savana 2500', 'metàlica', 'GMC');
insert into frame (model, frameType, brand) values ('Liberty', 'pasta', 'Jeep');
insert into frame (model, frameType, brand) values ('612 Scaglietti', 'pasta', 'Ferrari');
insert into frame (model, frameType, brand) values ('M', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('Silverado 1500', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Sierra 1500', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('Century', 'flotant', 'Buick');
insert into frame (model, frameType, brand) values ('Topaz', 'metàlica', 'Mercury');
insert into frame (model, frameType, brand) values ('Century', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('Z4', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('Express 2500', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Regal', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('Sunbird', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('CC', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Sentra', 'flotant', 'Nissan');
insert into frame (model, frameType, brand) values ('Camry', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Familia', 'metàlica', 'Mazda');
insert into frame (model, frameType, brand) values ('Aztek', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Town Car', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('Tundra', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Town Car', 'metàlica', 'Lincoln');
insert into frame (model, frameType, brand) values ('Explorer', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Sebring', 'flotant', 'Chrysler');
insert into frame (model, frameType, brand) values ('4Runner', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('4Runner', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('CX-7', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('Brooklands', 'flotant', 'Bentley');
insert into frame (model, frameType, brand) values ('VS Commodore', 'metàlica', 'Holden');
insert into frame (model, frameType, brand) values ('M3', 'pasta', 'BMW');
insert into frame (model, frameType, brand) values ('Outlander Sport', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Sunfire', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Rio', 'flotant', 'Kia');
insert into frame (model, frameType, brand) values ('Caravan', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('G', 'pasta', 'Infiniti');
insert into frame (model, frameType, brand) values ('Montana SV6', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Routan', 'metàlica', 'Volkswagen');
insert into frame (model, frameType, brand) values ('SL-Class', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Impala', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Century', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('Town & Country', 'pasta', 'Chrysler');
insert into frame (model, frameType, brand) values ('E150', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Tahoe', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Carens', 'flotant', 'Kia');
insert into frame (model, frameType, brand) values ('Ram 50', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('A4', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('C-Class', 'metàlica', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Canyon', 'metàlica', 'GMC');
insert into frame (model, frameType, brand) values ('Azera', 'pasta', 'Hyundai');
insert into frame (model, frameType, brand) values ('FJ Cruiser', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('1500 Club Coupe', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('Montero Sport', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Justy', 'flotant', 'Subaru');
insert into frame (model, frameType, brand) values ('Equator', 'metàlica', 'Suzuki');
insert into frame (model, frameType, brand) values ('LaCrosse', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('S10 Blazer', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Ascender', 'pasta', 'Isuzu');
insert into frame (model, frameType, brand) values ('Firebird Trans Am', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('LS', 'metàlica', 'Lexus');
insert into frame (model, frameType, brand) values ('Quest', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('Ram Van 1500', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('Envoy', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('760', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Rendezvous', 'flotant', 'Buick');
insert into frame (model, frameType, brand) values ('Protege', 'flotant', 'Mazda');
insert into frame (model, frameType, brand) values ('Silverado 3500HD', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Protege', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('LX', 'metàlica', 'Lexus');
insert into frame (model, frameType, brand) values ('tC', 'pasta', 'Scion');
insert into frame (model, frameType, brand) values ('XLR-V', 'flotant', 'Cadillac');
insert into frame (model, frameType, brand) values ('Sephia', 'flotant', 'Kia');
insert into frame (model, frameType, brand) values ('Exige', 'metàlica', 'Lotus');
insert into frame (model, frameType, brand) values ('Odyssey', 'flotant', 'Honda');
insert into frame (model, frameType, brand) values ('Town & Country', 'flotant', 'Chrysler');
insert into frame (model, frameType, brand) values ('Grand Vitara', 'metàlica', 'Suzuki');
insert into frame (model, frameType, brand) values ('Roadmaster', 'metàlica', 'Buick');
insert into frame (model, frameType, brand) values ('Outlander', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Tercel', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('XC90', 'pasta', 'Volvo');
insert into frame (model, frameType, brand) values ('Montana', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('Prelude', 'metàlica', 'Honda');
insert into frame (model, frameType, brand) values ('Sunfire', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('RX', 'metàlica', 'Lexus');
insert into frame (model, frameType, brand) values ('Quattroporte', 'flotant', 'Maserati');
insert into frame (model, frameType, brand) values ('Tracker', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Aviator', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('1500 Club Coupe', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('Express 1500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Corvette', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Rodeo Sport', 'pasta', 'Isuzu');
insert into frame (model, frameType, brand) values ('Alpina B7', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Grand Prix', 'flotant', 'Pontiac');
insert into frame (model, frameType, brand) values ('Sierra 2500', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('PT Cruiser', 'flotant', 'Chrysler');
insert into frame (model, frameType, brand) values ('Seville', 'pasta', 'Cadillac');
insert into frame (model, frameType, brand) values ('Acclaim', 'flotant', 'Plymouth');
insert into frame (model, frameType, brand) values ('Elantra', 'pasta', 'Hyundai');
insert into frame (model, frameType, brand) values ('Parisienne', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('RAV4', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('A6', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Mirage', 'flotant', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Prius', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('F-Series', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('MX-3', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('5 Series', 'metàlica', 'BMW');
insert into frame (model, frameType, brand) values ('Expedition EL', 'metàlica', 'Ford');
insert into frame (model, frameType, brand) values ('Legacy', 'flotant', 'Subaru');
insert into frame (model, frameType, brand) values ('Neon', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('Imperial', 'pasta', 'Chrysler');
insert into frame (model, frameType, brand) values ('Cabriolet', 'flotant', 'Audi');
insert into frame (model, frameType, brand) values ('Swift', 'pasta', 'Suzuki');
insert into frame (model, frameType, brand) values ('Z8', 'flotant', 'BMW');
insert into frame (model, frameType, brand) values ('Continental', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('Armada', 'pasta', 'Nissan');
insert into frame (model, frameType, brand) values ('Grand Prix', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('Explorer', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Windstar', 'pasta', 'Ford');
insert into frame (model, frameType, brand) values ('Corolla', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('3 Series', 'flotant', 'BMW');
insert into frame (model, frameType, brand) values ('S60', 'metàlica', 'Volvo');
insert into frame (model, frameType, brand) values ('Savana 1500', 'flotant', 'GMC');
insert into frame (model, frameType, brand) values ('CL', 'flotant', 'Acura');
insert into frame (model, frameType, brand) values ('968', 'flotant', 'Porsche');
insert into frame (model, frameType, brand) values ('Vision', 'flotant', 'Eagle');
insert into frame (model, frameType, brand) values ('Acclaim', 'flotant', 'Plymouth');
insert into frame (model, frameType, brand) values ('Xterra', 'metàlica', 'Nissan');
insert into frame (model, frameType, brand) values ('SX4', 'metàlica', 'Suzuki');
insert into frame (model, frameType, brand) values ('GL-Class', 'flotant', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Astro', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('S60', 'pasta', 'Volvo');
insert into frame (model, frameType, brand) values ('Mirage', 'pasta', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Discovery', 'flotant', 'Land Rover');
insert into frame (model, frameType, brand) values ('Ram 2500 Club', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('F250', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Vandura 3500', 'pasta', 'GMC');
insert into frame (model, frameType, brand) values ('S5', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Corvette', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('LS Hybrid', 'pasta', 'Lexus');
insert into frame (model, frameType, brand) values ('LaCrosse', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('300', 'metàlica', 'Chrysler');
insert into frame (model, frameType, brand) values ('Cobalt SS', 'pasta', 'Chevrolet');
insert into frame (model, frameType, brand) values ('RAV4', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Prius Plug-in Hybrid', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('SL-Class', 'pasta', 'Mercedes-Benz');
insert into frame (model, frameType, brand) values ('Taurus X', 'flotant', 'Ford');
insert into frame (model, frameType, brand) values ('Express 1500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Summit', 'metàlica', 'Eagle');
insert into frame (model, frameType, brand) values ('SX4', 'metàlica', 'Suzuki');
insert into frame (model, frameType, brand) values ('Mirage', 'metàlica', 'Mitsubishi');
insert into frame (model, frameType, brand) values ('Mulsanne', 'metàlica', 'Bentley');
insert into frame (model, frameType, brand) values ('Silverado 3500', 'metàlica', 'Chevrolet');
insert into frame (model, frameType, brand) values ('MKX', 'metàlica', 'Lincoln');
insert into frame (model, frameType, brand) values ('Impreza', 'flotant', 'Subaru');
insert into frame (model, frameType, brand) values ('Lumina', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Grand Prix', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('LS', 'flotant', 'Lincoln');
insert into frame (model, frameType, brand) values ('90', 'metàlica', 'Audi');
insert into frame (model, frameType, brand) values ('Ram 2500 Club', 'flotant', 'Dodge');
insert into frame (model, frameType, brand) values ('Vibe', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Grand Prix', 'pasta', 'Pontiac');
insert into frame (model, frameType, brand) values ('Cabriolet', 'flotant', 'Volkswagen');
insert into frame (model, frameType, brand) values ('Sienna', 'flotant', 'Toyota');
insert into frame (model, frameType, brand) values ('Town Car', 'metàlica', 'Lincoln');
insert into frame (model, frameType, brand) values ('Sonata', 'pasta', 'Hyundai');
insert into frame (model, frameType, brand) values ('Ram 2500', 'flotant', 'Dodge');
insert into frame (model, frameType, brand) values ('Passat', 'pasta', 'Volkswagen');
insert into frame (model, frameType, brand) values ('MR2', 'metàlica', 'Toyota');
insert into frame (model, frameType, brand) values ('Celica', 'pasta', 'Toyota');
insert into frame (model, frameType, brand) values ('Navigator L', 'flotant', 'Lincoln');
insert into frame (model, frameType, brand) values ('Intrepid', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('Spirit', 'metàlica', 'Dodge');
insert into frame (model, frameType, brand) values ('RL', 'pasta', 'Acura');
insert into frame (model, frameType, brand) values ('MX-6', 'pasta', 'Mazda');
insert into frame (model, frameType, brand) values ('Tahoe', 'flotant', 'Chevrolet');
insert into frame (model, frameType, brand) values ('Grand Prix', 'metàlica', 'Pontiac');
insert into frame (model, frameType, brand) values ('Pilot', 'pasta', 'Honda');
insert into frame (model, frameType, brand) values ('MKX', 'pasta', 'Lincoln');
insert into frame (model, frameType, brand) values ('Boxster', 'flotant', 'Porsche');
insert into frame (model, frameType, brand) values ('Vision', 'flotant', 'Eagle');
insert into frame (model, frameType, brand) values ('FF', 'metàlica', 'Ferrari');
insert into frame (model, frameType, brand) values ('LeSabre', 'pasta', 'Buick');
insert into frame (model, frameType, brand) values ('Justy', 'pasta', 'Subaru');
insert into frame (model, frameType, brand) values ('Town & Country', 'pasta', 'Chrysler');
insert into frame (model, frameType, brand) values ('Tribeca', 'flotant', 'Subaru');
insert into frame (model, frameType, brand) values ('Grand Caravan', 'pasta', 'Dodge');
insert into frame (model, frameType, brand) values ('B-Series Plus', 'metàlica', 'Mazda');
insert into frame (model, frameType, brand) values ('Esprit', 'metàlica', 'Lotus');
