insert into picture (title, dimensions, author_idAuthor) values ('They Call Us Misfits (Dom kallar oss mods)', '133.7x434.6', 62);
insert into picture (title, dimensions, author_idAuthor) values ('Let''s Not Keep in Touch!', '569.5x653.6', 53);
insert into picture (title, dimensions, author_idAuthor) values ('Fantomas Unleashed', '519.3x642.9', 77);
insert into picture (title, dimensions, author_idAuthor) values ('Cheap Detective, The', '704.5x497.3', 56);
insert into picture (title, dimensions, author_idAuthor) values ('It''s Alive III: Island of the Alive', '109.1x879.8', 57);
insert into picture (title, dimensions, author_idAuthor) values ('Trials of Henry Kissinger, The', '546.5x874.7', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Pollock', '770.1x078.3', 99);
insert into picture (title, dimensions, author_idAuthor) values ('Red Dawn', '407.3x334.5', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Charlie, the Lonesome Cougar', '483.7x540.2', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Life or Something Like It', '327.6x525.6', 54);
insert into picture (title, dimensions, author_idAuthor) values ('War of the Gargantuas, The (Furankenshutain no kaijû: Sanda tai Gaira)', '906.7x122.0', 41);
insert into picture (title, dimensions, author_idAuthor) values ('Life of Oharu, The (Saikaku ichidai onna)', '113.0x422.6', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Protector, The (a.k.a. Warrior King) (Tom yum goong)', '830.6x534.1', 19);
insert into picture (title, dimensions, author_idAuthor) values ('Big Tease, The', '936.6x012.8', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Lumiere and Company (Lumière et compagnie)', '707.1x295.5', 5);
insert into picture (title, dimensions, author_idAuthor) values ('What If', '249.9x214.1', 56);
insert into picture (title, dimensions, author_idAuthor) values ('SuperBabies: Baby Geniuses 2', '509.4x171.1', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Front, The', '055.8x679.2', 80);
insert into picture (title, dimensions, author_idAuthor) values ('Without a Clue', '391.8x420.6', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Wall Street', '767.1x017.4', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Legend of Bigfoot, The', '900.0x696.0', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Red Hook Summer', '136.5x588.7', 13);
insert into picture (title, dimensions, author_idAuthor) values ('My Dog Tulip', '963.1x445.8', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Happy Ever Afters', '866.9x055.1', 55);
insert into picture (title, dimensions, author_idAuthor) values ('Los Flamencos', '456.5x211.3', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Merry Widow, The', '569.3x344.8', 88);
insert into picture (title, dimensions, author_idAuthor) values ('Survival of the Dead', '369.0x480.5', 54);
insert into picture (title, dimensions, author_idAuthor) values ('Attila Marcel', '162.1x758.5', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Twin Dragons (Shuang long hui)', '380.9x778.3', 80);
insert into picture (title, dimensions, author_idAuthor) values ('Taking of Pelham One Two Three, The', '673.8x293.3', 8);
insert into picture (title, dimensions, author_idAuthor) values ('Gambler, The', '693.3x343.3', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Breakfast at Tiffany''s', '676.4x582.7', 23);
insert into picture (title, dimensions, author_idAuthor) values ('Anastasia', '292.9x279.8', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Desert Flower', '511.4x180.0', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Woodstock', '273.4x859.1', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Naked Killer (Chik loh go yeung)', '266.2x142.2', 82);
insert into picture (title, dimensions, author_idAuthor) values ('All Quiet on the Western Front', '499.1x287.0', 15);
insert into picture (title, dimensions, author_idAuthor) values ('Blade', '166.1x498.8', 83);
insert into picture (title, dimensions, author_idAuthor) values ('National Lampoon''s Senior Trip', '069.0x620.0', 54);
insert into picture (title, dimensions, author_idAuthor) values ('Lake Placid', '805.8x504.6', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Rage (Rabia)', '965.1x710.6', 12);
insert into picture (title, dimensions, author_idAuthor) values ('No. 1 Ladies'' Detective Agency, The', '897.3x720.7', 15);
insert into picture (title, dimensions, author_idAuthor) values ('Forest (Rengeteg)', '591.8x517.4', 41);
insert into picture (title, dimensions, author_idAuthor) values ('Devil to Pay!, The', '141.1x530.9', 53);
insert into picture (title, dimensions, author_idAuthor) values ('Acapulco, First Beach... To the Left', '447.9x735.0', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Ned Kelly', '897.6x680.9', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Three Men and a Cradle (3 hommes et un couffin)', '235.7x888.2', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Unknown', '598.4x357.3', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Thomas and the Magic Railroad', '208.6x198.0', 22);
insert into picture (title, dimensions, author_idAuthor) values ('Secrets, The (Sodot, Ha-)', '621.2x525.5', 27);
insert into picture (title, dimensions, author_idAuthor) values ('H-Man, The (Bijo to Ekitainingen)', '396.1x444.9', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Trials of Darryl Hunt, The', '180.2x394.7', 79);
insert into picture (title, dimensions, author_idAuthor) values ('Bishop Murder Case, The', '363.5x847.6', 87);
insert into picture (title, dimensions, author_idAuthor) values ('Letter Never Sent (Neotpravlennoye pismo)', '762.8x536.1', 33);
insert into picture (title, dimensions, author_idAuthor) values ('In the Basement', '251.7x930.0', 19);
insert into picture (title, dimensions, author_idAuthor) values ('Tripper, The', '789.3x006.2', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Synchromy', '387.8x510.8', 64);
insert into picture (title, dimensions, author_idAuthor) values ('Kon-Tiki', '669.2x292.3', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Crossover', '076.7x288.8', 53);
insert into picture (title, dimensions, author_idAuthor) values ('Mothra (Mosura)', '652.3x483.3', 6);
insert into picture (title, dimensions, author_idAuthor) values ('Twins', '419.5x221.7', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Shag', '927.7x314.6', 77);
insert into picture (title, dimensions, author_idAuthor) values ('July Rhapsody (Laam yan sei sap)', '167.0x453.7', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Dim Sum: A Little Bit of Heart', '394.2x378.4', 3);
insert into picture (title, dimensions, author_idAuthor) values ('Serenity', '392.3x325.6', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Code of Silence', '528.4x698.8', 52);
insert into picture (title, dimensions, author_idAuthor) values ('Prodigal Son, The (Tuhlaajapoika)', '106.1x681.3', 13);
insert into picture (title, dimensions, author_idAuthor) values ('Pirates', '037.9x837.4', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Isn''t She Great?', '363.6x614.5', 25);
insert into picture (title, dimensions, author_idAuthor) values ('Troll in Central Park, A', '782.4x396.7', 76);
insert into picture (title, dimensions, author_idAuthor) values ('One Way Boogie Woogie', '230.3x373.2', 64);
insert into picture (title, dimensions, author_idAuthor) values ('Major Payne', '902.4x394.7', 24);
insert into picture (title, dimensions, author_idAuthor) values ('The Joy of Living', '807.3x698.8', 78);
insert into picture (title, dimensions, author_idAuthor) values ('Bon Cop, Bad Cop', '399.4x416.6', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Traffic', '832.2x932.3', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Morvern Callar', '756.5x653.6', 41);
insert into picture (title, dimensions, author_idAuthor) values ('Apartment 1303', '047.3x231.2', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Wish I Was Here', '525.5x130.4', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Boot, Das (Boat, The)', '346.7x450.2', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Twelfth Night', '044.9x217.2', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Flamingo Kid, The', '455.6x749.5', 29);
insert into picture (title, dimensions, author_idAuthor) values ('Bride Came C.O.D., The', '748.3x533.5', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Red-Headed Woman', '730.0x057.2', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Joe Gould''s Secret', '341.4x208.1', 33);
insert into picture (title, dimensions, author_idAuthor) values ('Maze, The', '226.0x821.1', 79);
insert into picture (title, dimensions, author_idAuthor) values ('Eaux d''artifice', '906.4x498.7', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Home of the Brave', '134.4x776.5', 23);
insert into picture (title, dimensions, author_idAuthor) values ('Human Lanterns (Ren pi deng long)', '838.5x685.8', 6);
insert into picture (title, dimensions, author_idAuthor) values ('Dynamite', '086.1x913.7', 46);
insert into picture (title, dimensions, author_idAuthor) values ('That Old Feeling', '652.5x680.5', 27);
insert into picture (title, dimensions, author_idAuthor) values ('Fool There Was, A', '821.7x725.4', 9);
insert into picture (title, dimensions, author_idAuthor) values ('Our Summer in Provence', '689.1x942.9', 27);
insert into picture (title, dimensions, author_idAuthor) values ('Up in Smoke', '747.4x423.4', 79);
insert into picture (title, dimensions, author_idAuthor) values ('Those Who Love Me Can Take the Train (Ceux qui m''aiment prendront le train)', '293.2x622.8', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Koumiko Mystery, The (Mystère Koumiko, Le)', '348.0x243.7', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Free Money', '921.8x437.7', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Next of Kin', '350.6x931.2', 13);
insert into picture (title, dimensions, author_idAuthor) values ('Bob Funk', '757.3x133.9', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Spud', '418.7x792.6', 37);
insert into picture (title, dimensions, author_idAuthor) values ('Terrorist, The (a.k.a. Malli) (Theeviravaathi)', '124.9x865.3', 16);
insert into picture (title, dimensions, author_idAuthor) values ('Love and Pain and the Whole Damn Thing', '178.5x867.9', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Bell Boy, The', '473.6x933.2', 28);
insert into picture (title, dimensions, author_idAuthor) values ('Mischief', '155.4x651.2', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Take a Giant Step', '957.8x124.8', 72);
insert into picture (title, dimensions, author_idAuthor) values ('Combat Girls (Kriegerin)', '573.3x440.7', 45);
insert into picture (title, dimensions, author_idAuthor) values ('Blondie of the Follies', '378.3x533.2', 87);
insert into picture (title, dimensions, author_idAuthor) values ('Thorn in the Heart, The', '272.0x631.3', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Corridor, The (Koridorius)', '479.9x084.0', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Mother and Child', '707.0x530.0', 90);
insert into picture (title, dimensions, author_idAuthor) values ('Colour of Magic, The (Terry Pratchett''s The Colour of Magic)', '637.7x165.4', 36);
insert into picture (title, dimensions, author_idAuthor) values ('Winter Sleep (Kis Uykusu)', '499.6x317.7', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Fuck', '456.0x324.5', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Fade To Black', '244.9x553.4', 17);
insert into picture (title, dimensions, author_idAuthor) values ('In the Name of the Father', '848.6x690.2', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Woman in Black, The', '490.0x397.0', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Rent', '278.5x141.2', 57);
insert into picture (title, dimensions, author_idAuthor) values ('Step Brothers', '989.8x218.1', 6);
insert into picture (title, dimensions, author_idAuthor) values ('Haunting of Molly Hartley, The', '221.2x256.5', 58);
insert into picture (title, dimensions, author_idAuthor) values ('Hidden Agenda', '904.5x560.1', 63);
insert into picture (title, dimensions, author_idAuthor) values ('Selena', '562.3x892.4', 30);
insert into picture (title, dimensions, author_idAuthor) values ('Godzilla: Tokyo S.O.S. (Gojira tai Mosura tai Mekagojira: Tôkyô S.O.S.)', '803.6x111.6', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Camille', '597.9x145.3', 11);
insert into picture (title, dimensions, author_idAuthor) values ('Death in the Garden (Mort en ce jardin, La)', '281.4x072.6', 40);
insert into picture (title, dimensions, author_idAuthor) values ('Rainbow Valley', '882.0x959.9', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Murder at 1600', '263.2x934.0', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Deliver Us from Eva', '917.0x386.0', 59);
insert into picture (title, dimensions, author_idAuthor) values ('It Felt Like Love', '083.6x488.4', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Bad News Bears in Breaking Training, The', '866.6x321.6', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Jersey Girl', '507.1x780.7', 41);
insert into picture (title, dimensions, author_idAuthor) values ('Bustin'' Loose', '111.1x474.9', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Fear and Loathing in Las Vegas', '232.8x527.2', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Exploding Girl, The', '278.6x690.5', 4);
insert into picture (title, dimensions, author_idAuthor) values ('Intentions of Murder (a.k.a. Murderous Instincts) (Akai satsui)', '426.8x823.4', 20);
insert into picture (title, dimensions, author_idAuthor) values ('The D Train', '320.7x572.1', 99);
insert into picture (title, dimensions, author_idAuthor) values ('The Disappeared', '282.3x210.7', 87);
insert into picture (title, dimensions, author_idAuthor) values ('Good Guy, The', '655.9x204.4', 78);
insert into picture (title, dimensions, author_idAuthor) values ('Wrong Rosary (Uzak ihtimal)', '297.7x299.4', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Europa Report', '552.3x159.3', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Ride in the Whirlwind', '379.8x249.5', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Kingdom, The (Riget)', '016.3x764.4', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Dating the Enemy', '442.6x031.7', 71);
insert into picture (title, dimensions, author_idAuthor) values ('Crimes Against Humanity', '372.2x993.5', 26);
insert into picture (title, dimensions, author_idAuthor) values ('Sebastian Maniscalco: What''s Wrong with People?', '667.6x119.4', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Elektra Luxx', '706.4x108.9', 68);
insert into picture (title, dimensions, author_idAuthor) values ('Notorious Landlady, The', '006.6x950.8', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Cowboy Bebop', '502.2x379.2', 36);
insert into picture (title, dimensions, author_idAuthor) values ('And Soon the Darkness', '785.6x698.0', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Drum, The (Drums)', '029.6x527.6', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Empire of the Ants', '670.1x942.9', 88);
insert into picture (title, dimensions, author_idAuthor) values ('First Sunday', '834.5x140.1', 28);
insert into picture (title, dimensions, author_idAuthor) values ('Hateship Loveship', '762.0x144.8', 10);
insert into picture (title, dimensions, author_idAuthor) values ('Charleston', '653.9x780.1', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Mickey, Donald, Goofy: The Three Musketeers', '304.4x195.5', 84);
insert into picture (title, dimensions, author_idAuthor) values ('He Ran All the Way', '330.5x233.7', 65);
insert into picture (title, dimensions, author_idAuthor) values ('Barney''s Great Adventure', '174.6x832.0', 36);
insert into picture (title, dimensions, author_idAuthor) values ('St. Valentine''s Day Massacre, The', '349.2x795.7', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Hilary and Jackie', '489.5x726.8', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Broderskab (Brotherhood)', '124.6x262.1', 40);
insert into picture (title, dimensions, author_idAuthor) values ('On Tour (Tournée)', '154.7x108.6', 4);
insert into picture (title, dimensions, author_idAuthor) values ('Zhou Yu''s Train (Zhou Yu de huo che)', '826.4x177.6', 57);
insert into picture (title, dimensions, author_idAuthor) values ('In Custody', '087.3x404.8', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Olsen Gang on the Track, The (Olsen-banden på sporet)', '502.4x533.0', 90);
insert into picture (title, dimensions, author_idAuthor) values ('Bridget Jones''s Diary', '001.1x978.5', 10);
insert into picture (title, dimensions, author_idAuthor) values ('No End in Sight', '783.3x026.2', 46);
insert into picture (title, dimensions, author_idAuthor) values ('2 + 2 (Dos más dos)', '492.9x584.7', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Loch Ness', '597.2x488.4', 42);
insert into picture (title, dimensions, author_idAuthor) values ('13 Fighting Men', '048.6x319.6', 66);
insert into picture (title, dimensions, author_idAuthor) values ('Two-Way Stretch', '312.7x638.4', 71);
insert into picture (title, dimensions, author_idAuthor) values ('Broken City', '189.4x949.7', 62);
insert into picture (title, dimensions, author_idAuthor) values ('National Treasure', '072.4x640.0', 62);
insert into picture (title, dimensions, author_idAuthor) values ('Three Degrees Colder (3° kälter)', '104.7x922.9', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Army of Crime (L''armée du crime)', '272.8x698.7', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Witch Who Came from the Sea, The', '437.5x391.3', 17);
insert into picture (title, dimensions, author_idAuthor) values ('Poker House, The', '636.0x340.3', 21);
insert into picture (title, dimensions, author_idAuthor) values ('Grave Decisions (Wer früher stirbt, ist länger tot)', '814.2x319.9', 24);
insert into picture (title, dimensions, author_idAuthor) values ('Once in the Life', '465.3x825.8', 67);
insert into picture (title, dimensions, author_idAuthor) values ('Sundown', '317.1x815.9', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Dumb and Dumber To', '054.3x993.2', 47);
insert into picture (title, dimensions, author_idAuthor) values ('Demonic', '286.7x190.4', 7);
insert into picture (title, dimensions, author_idAuthor) values ('Brother Minister: The Assassination of Malcolm X', '747.6x885.3', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Chair, The', '440.3x260.7', 97);
insert into picture (title, dimensions, author_idAuthor) values ('High School Musical 3: Senior Year', '180.8x462.9', 76);
insert into picture (title, dimensions, author_idAuthor) values ('This So-Called Disaster', '812.9x512.6', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Nowhere Boy', '918.5x775.0', 52);
insert into picture (title, dimensions, author_idAuthor) values ('Lost Embrace (Abrazo partido, El)', '917.1x934.2', 72);
insert into picture (title, dimensions, author_idAuthor) values ('Pope of Greenwich Village, The', '282.2x362.5', 14);
insert into picture (title, dimensions, author_idAuthor) values ('We Won''t Grow Old Together (Nous ne vieillirons pas ensemble)', '010.4x475.1', 72);
insert into picture (title, dimensions, author_idAuthor) values ('Alien Cargo', '825.0x241.7', 94);
insert into picture (title, dimensions, author_idAuthor) values ('Hollywood or Bust', '578.0x342.0', 10);
insert into picture (title, dimensions, author_idAuthor) values ('End of the Line', '733.3x307.6', 25);
insert into picture (title, dimensions, author_idAuthor) values ('Il Mare (Siworae)', '798.4x619.1', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Innocent Sleep, The', '058.7x772.3', 10);
insert into picture (title, dimensions, author_idAuthor) values ('This Gun for Hire', '349.5x817.0', 88);
insert into picture (title, dimensions, author_idAuthor) values ('Shout, The', '566.9x564.3', 37);
insert into picture (title, dimensions, author_idAuthor) values ('Ethan Frome', '592.7x432.0', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Survival Island (Three)', '453.0x862.9', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Year of the Jellyfish (L''année des méduses)', '696.0x054.6', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Dead Time: Kala', '005.6x301.0', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Black Mirror', '966.0x982.5', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Forbidden Kingdom, The', '684.4x051.0', 41);
insert into picture (title, dimensions, author_idAuthor) values ('National Treasure', '656.5x392.3', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Rude', '122.4x750.4', 80);
insert into picture (title, dimensions, author_idAuthor) values ('Dead Presidents', '425.8x670.3', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Late Autumn (Akibiyori)', '089.8x353.8', 17);
insert into picture (title, dimensions, author_idAuthor) values ('Body and Soul', '825.2x352.7', 72);
insert into picture (title, dimensions, author_idAuthor) values ('Lincz', '399.6x309.8', 55);
insert into picture (title, dimensions, author_idAuthor) values ('French Minister, The (Quai d''Orsay)', '613.8x698.5', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Natural Born Killers', '612.2x961.8', 66);
insert into picture (title, dimensions, author_idAuthor) values ('A-Team, The', '430.7x610.7', 71);
insert into picture (title, dimensions, author_idAuthor) values ('Gothic', '111.5x815.8', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Two Queens and One Consort (Twee vorstinnen en een vorst)', '917.9x807.8', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Waterboy, The', '043.6x408.7', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Serial Killer Culture', '321.0x390.1', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Night of the Hunter, The', '168.2x815.8', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Lizard in a Woman''s Skin, A (Lucertola con la pelle di donna, Una)', '897.4x526.0', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Young at Heart (a.k.a. Young@Heart)', '860.3x059.5', 28);
insert into picture (title, dimensions, author_idAuthor) values ('Commune, La (Paris, 1871)', '163.3x738.9', 64);
insert into picture (title, dimensions, author_idAuthor) values ('Café Lumière (Kôhî jikô)', '804.6x662.3', 47);
insert into picture (title, dimensions, author_idAuthor) values ('Gun Fury', '057.4x360.9', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Sixteen Candles', '679.3x564.3', 53);
insert into picture (title, dimensions, author_idAuthor) values ('Lust for Gold', '548.8x175.0', 19);
insert into picture (title, dimensions, author_idAuthor) values ('Ella Lola, a la Trilby', '789.4x969.3', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Holiday, The', '360.6x268.7', 47);
insert into picture (title, dimensions, author_idAuthor) values ('Season of the Witch', '381.1x184.2', 98);
insert into picture (title, dimensions, author_idAuthor) values ('ParaNorman', '073.3x533.2', 95);
insert into picture (title, dimensions, author_idAuthor) values ('How to Eat Your Watermelon in White Company (and Enjoy It)', '175.4x486.4', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Shades of Ray', '875.7x074.1', 89);
insert into picture (title, dimensions, author_idAuthor) values ('The Girls', '854.7x997.1', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Unleashed (Danny the Dog)', '212.2x915.3', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Sorority House Massacre', '276.9x147.3', 38);
insert into picture (title, dimensions, author_idAuthor) values ('Panther', '087.7x793.6', 99);
insert into picture (title, dimensions, author_idAuthor) values ('The Periwig-Maker', '047.4x414.9', 86);
insert into picture (title, dimensions, author_idAuthor) values ('They Came Back (Les Revenants)', '753.5x121.2', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Evil Dead, The', '650.8x916.5', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Borderland', '405.2x015.1', 67);
insert into picture (title, dimensions, author_idAuthor) values ('Call Northside 777', '728.5x045.7', 38);
insert into picture (title, dimensions, author_idAuthor) values ('Painted Skin', '295.6x312.8', 77);
insert into picture (title, dimensions, author_idAuthor) values ('S.P.L.: Kill Zone (Saat po long)', '090.3x459.1', 45);
insert into picture (title, dimensions, author_idAuthor) values ('Fear Strikes Out', '158.8x989.9', 73);
insert into picture (title, dimensions, author_idAuthor) values ('Laramie Project, The', '611.4x945.7', 75);
insert into picture (title, dimensions, author_idAuthor) values ('Get Low', '274.4x420.1', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Bunny and the Bull', '485.5x787.4', 27);
insert into picture (title, dimensions, author_idAuthor) values ('Bloodstone: Subspecies II', '142.6x869.5', 29);
insert into picture (title, dimensions, author_idAuthor) values ('Juggernaut', '546.9x362.2', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Spare Parts', '376.7x824.6', 12);
insert into picture (title, dimensions, author_idAuthor) values ('20,000 Leagues Under the Sea', '582.0x217.8', 68);
insert into picture (title, dimensions, author_idAuthor) values ('A Night at the Movies: The Horrors of Stephen King', '170.2x211.9', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Darkon', '851.1x534.6', 9);
insert into picture (title, dimensions, author_idAuthor) values ('Zack and Miri Make a Porno', '008.8x083.8', 90);
insert into picture (title, dimensions, author_idAuthor) values ('Jack the Ripper', '999.4x743.1', 66);
insert into picture (title, dimensions, author_idAuthor) values ('Captain America II: Death Too Soon', '255.6x121.6', 26);
insert into picture (title, dimensions, author_idAuthor) values ('Day of the Locust, The', '274.0x100.2', 31);
insert into picture (title, dimensions, author_idAuthor) values ('Silent Witness (Do Not Disturb)', '986.2x404.5', 83);
insert into picture (title, dimensions, author_idAuthor) values ('Gunfighter, The', '835.9x435.7', 76);
insert into picture (title, dimensions, author_idAuthor) values ('12 Dates of Christmas', '698.4x267.7', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Christmas Carol, A (Scrooge)', '102.9x373.8', 64);
insert into picture (title, dimensions, author_idAuthor) values ('Contract, The', '807.5x757.8', 22);
insert into picture (title, dimensions, author_idAuthor) values ('God on Trial', '238.8x824.4', 88);
insert into picture (title, dimensions, author_idAuthor) values ('Black Lightning (Chernaya Molniya)', '798.0x194.4', 38);
insert into picture (title, dimensions, author_idAuthor) values ('House on Sorority Row, The', '449.0x550.1', 7);
insert into picture (title, dimensions, author_idAuthor) values ('Four Feathers, The', '508.0x528.3', 11);
insert into picture (title, dimensions, author_idAuthor) values ('First Love, Last Rites', '700.0x373.5', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Fearful Symmetry: The Making of ''To Kill a Mockingbird''', '949.3x189.9', 9);
insert into picture (title, dimensions, author_idAuthor) values ('Blablablá', '622.1x995.1', 75);
insert into picture (title, dimensions, author_idAuthor) values ('L.A. Confidential', '777.3x030.8', 49);
insert into picture (title, dimensions, author_idAuthor) values ('Through the Olive Trees (Zire darakhatan zeyton)', '944.8x746.8', 80);
insert into picture (title, dimensions, author_idAuthor) values ('Holidays by the Sea (Ni à vendre ni à louer)', '961.9x958.1', 13);
insert into picture (title, dimensions, author_idAuthor) values ('Grande école', '304.1x354.9', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Last Real Men, The (Die letzten Männer)', '277.1x500.7', 88);
insert into picture (title, dimensions, author_idAuthor) values ('Just a Sigh', '558.3x941.2', 25);
insert into picture (title, dimensions, author_idAuthor) values ('Superman III', '491.9x331.4', 94);
insert into picture (title, dimensions, author_idAuthor) values ('Haider', '823.3x553.2', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Love Is News', '110.1x302.4', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Boom!', '963.7x105.7', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Circle of Eight', '041.0x658.6', 99);
insert into picture (title, dimensions, author_idAuthor) values ('Christmas Story (Joulutarina)', '991.8x002.5', 94);
insert into picture (title, dimensions, author_idAuthor) values ('Kiss of the Vampire, The', '214.4x407.3', 31);
insert into picture (title, dimensions, author_idAuthor) values ('The Imitation Game', '037.5x711.2', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Heidi', '731.8x342.2', 17);
insert into picture (title, dimensions, author_idAuthor) values ('Scary Movie 4', '600.0x892.7', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Outcast of the Islands', '547.3x151.3', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Kissed by Winter (Vinterkyss)', '174.7x770.0', 87);
insert into picture (title, dimensions, author_idAuthor) values ('Make the Yuletide Gay', '779.6x940.3', 70);
insert into picture (title, dimensions, author_idAuthor) values ('Stars Above', '038.0x870.1', 56);
insert into picture (title, dimensions, author_idAuthor) values ('Porto of My Childhood (Porto da Minha Infância)', '423.7x749.7', 99);
insert into picture (title, dimensions, author_idAuthor) values ('Confessions of an Opium Eater', '366.7x128.7', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Door in the Floor, The', '680.4x108.2', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Love and a .45', '861.0x845.6', 97);
insert into picture (title, dimensions, author_idAuthor) values ('In the Realms of the Unreal', '507.1x894.1', 96);
insert into picture (title, dimensions, author_idAuthor) values ('Medea', '662.0x020.9', 42);
insert into picture (title, dimensions, author_idAuthor) values ('Borrower, The', '973.7x202.2', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Hangman''s Curse', '958.7x117.3', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Flavor of Green Tea Over Rice (Ochazuke no aji)', '060.5x329.9', 13);
insert into picture (title, dimensions, author_idAuthor) values ('Celine and Julie Go Boating (Celine et Julie vont en bateau)', '159.6x601.1', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Amen.', '533.0x277.9', 8);
insert into picture (title, dimensions, author_idAuthor) values ('Captive (Cautiva) ', '079.4x484.7', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Vampyros Lesbos (Vampiras, Las)', '968.3x371.3', 85);
insert into picture (title, dimensions, author_idAuthor) values ('Ajami', '517.8x675.6', 81);
insert into picture (title, dimensions, author_idAuthor) values ('To Have and Have Not', '060.4x322.0', 64);
insert into picture (title, dimensions, author_idAuthor) values ('Italian, The (Italianetz)', '651.0x880.8', 89);
insert into picture (title, dimensions, author_idAuthor) values ('Runaways, The', '440.8x482.8', 54);
insert into picture (title, dimensions, author_idAuthor) values ('Konopielka', '308.8x591.6', 8);
insert into picture (title, dimensions, author_idAuthor) values ('Almost Married', '396.1x355.3', 57);
insert into picture (title, dimensions, author_idAuthor) values ('Joni''s Promise', '234.6x324.5', 83);
insert into picture (title, dimensions, author_idAuthor) values ('8th Wonderland', '094.3x096.9', 78);
insert into picture (title, dimensions, author_idAuthor) values ('Charlie Chan in Rio', '478.2x538.9', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Don''t Make Waves', '174.5x833.0', 58);
insert into picture (title, dimensions, author_idAuthor) values ('Seven Years Bad Luck', '259.7x722.5', 89);
insert into picture (title, dimensions, author_idAuthor) values ('Manhattan Baby', '933.9x308.6', 6);
insert into picture (title, dimensions, author_idAuthor) values ('Suspicion', '569.3x774.9', 58);
insert into picture (title, dimensions, author_idAuthor) values ('Strange Little Cat, The (Das merkwürdige Kätzchen)', '573.0x412.0', 54);
insert into picture (title, dimensions, author_idAuthor) values ('Green Fire', '021.1x372.3', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Garbage Pail Kids Movie, The', '660.5x697.8', 68);
insert into picture (title, dimensions, author_idAuthor) values ('Get Low', '538.2x717.4', 7);
insert into picture (title, dimensions, author_idAuthor) values ('Showgirls', '692.9x615.3', 29);
insert into picture (title, dimensions, author_idAuthor) values ('Chinese Box', '984.9x153.0', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Beyond, The (E tu vivrai nel terrore - L''aldilà)', '841.1x391.7', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Zachariah', '521.5x258.2', 68);
insert into picture (title, dimensions, author_idAuthor) values ('Wayward Cloud, The (Tian bian yi duo yun)', '703.4x372.8', 7);
insert into picture (title, dimensions, author_idAuthor) values ('National Lampoon''s Senior Trip', '558.8x466.5', 68);
insert into picture (title, dimensions, author_idAuthor) values ('Rudderless', '693.9x676.1', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Body/Cialo', '515.9x655.2', 73);
insert into picture (title, dimensions, author_idAuthor) values ('Blob, The', '929.4x344.7', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Admission', '732.4x414.7', 77);
insert into picture (title, dimensions, author_idAuthor) values ('Viridiana', '351.3x133.2', 6);
insert into picture (title, dimensions, author_idAuthor) values ('Transporter 2', '813.1x660.9', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Gay Deceivers, The', '709.9x824.7', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Name for Evil, A', '235.7x826.1', 67);
insert into picture (title, dimensions, author_idAuthor) values ('Two in the Wave', '388.7x167.8', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Unknown Woman, The (La Sconosciuta)', '296.9x346.3', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Goke, Body Snatcher from Hell (Kyuketsuki Gokemidoro)', '334.4x042.7', 3);
insert into picture (title, dimensions, author_idAuthor) values ('Charlie Chan''s Greatest Case', '379.7x448.2', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Wing and a Prayer', '240.8x455.5', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Machine Girl, The (Kataude mashin gâru)', '902.8x311.2', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Full Tilt Boogie', '141.2x918.7', 96);
insert into picture (title, dimensions, author_idAuthor) values ('Shadow People', '859.0x044.5', 61);
insert into picture (title, dimensions, author_idAuthor) values ('There''s No Business Like Show Business', '657.9x206.2', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Hero Wanted', '574.6x863.0', 27);
insert into picture (title, dimensions, author_idAuthor) values ('Everything', '205.4x136.9', 22);
insert into picture (title, dimensions, author_idAuthor) values ('Robot', '349.0x788.4', 17);
insert into picture (title, dimensions, author_idAuthor) values ('Honey Pot, The', '868.5x216.6', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Jack Brooks: Monster Slayer', '155.1x541.2', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Facing Ali', '645.3x255.8', 60);
insert into picture (title, dimensions, author_idAuthor) values ('Waiting...', '495.0x400.0', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Beyond (Svinalängorna)', '647.5x945.4', 17);
insert into picture (title, dimensions, author_idAuthor) values ('Three Men and a Baby', '521.3x353.9', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Bethlehem', '716.5x751.1', 27);
insert into picture (title, dimensions, author_idAuthor) values ('Hop', '796.6x055.0', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Limit (Limite)', '709.6x475.7', 66);
insert into picture (title, dimensions, author_idAuthor) values ('Biutiful', '519.9x894.8', 30);
insert into picture (title, dimensions, author_idAuthor) values ('Salt', '914.0x734.2', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Night Train to Munich', '425.0x894.4', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Redemption of General Butt Naked, The', '391.3x667.8', 7);
insert into picture (title, dimensions, author_idAuthor) values ('Duel at Silver Creek, The', '988.7x430.8', 89);
insert into picture (title, dimensions, author_idAuthor) values ('29 Palms', '204.3x648.1', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Ice-Cold in Alex', '544.0x751.5', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Action Jackson', '755.6x020.5', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Otakus in Love', '164.2x816.0', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Love and Basketball', '579.4x307.7', 13);
insert into picture (title, dimensions, author_idAuthor) values ('Faithless (Trolösa)', '005.9x893.9', 5);
insert into picture (title, dimensions, author_idAuthor) values ('Lady Terminator (Pembalasan ratu pantai selatan)', '881.8x235.2', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Cinema Verite', '818.5x701.2', 11);
insert into picture (title, dimensions, author_idAuthor) values ('A Cinderella Story: Once Upon a Song', '616.0x320.4', 71);
insert into picture (title, dimensions, author_idAuthor) values ('For Richer or Poorer', '472.2x907.0', 54);
insert into picture (title, dimensions, author_idAuthor) values ('Cold Prey II (Fritt Vilt II)', '740.1x864.9', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Countess Dracula', '042.2x073.2', 99);
insert into picture (title, dimensions, author_idAuthor) values ('Svengali', '940.6x103.8', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Gray Lady Down', '389.7x080.2', 40);
insert into picture (title, dimensions, author_idAuthor) values ('No Man''s Land', '548.0x587.2', 33);
insert into picture (title, dimensions, author_idAuthor) values ('Last Ride', '249.1x480.6', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Ingmar Bergman Makes a Movie (Ingmar Bergman gör en film)', '119.7x062.3', 5);
insert into picture (title, dimensions, author_idAuthor) values ('Amish Murder, An', '555.3x991.2', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Devil and Daniel Webster, The (All That Money Can Buy)', '475.5x969.0', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Magnificent Seven, The', '945.5x356.5', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Wishful Drinking', '399.6x317.6', 11);
insert into picture (title, dimensions, author_idAuthor) values ('Benjamin Blümchen - Seine schönsten Abenteuer', '122.2x380.4', 53);
insert into picture (title, dimensions, author_idAuthor) values ('The Valley of Gwangi', '827.7x741.4', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Someone''s Gaze', '338.1x036.1', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Twelve', '755.3x621.3', 65);
insert into picture (title, dimensions, author_idAuthor) values ('Holiday in Handcuffs', '732.6x594.7', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Dive! (Dive!: Living off America''s Waste)', '332.1x933.7', 30);
insert into picture (title, dimensions, author_idAuthor) values ('Better Place, A', '238.1x055.4', 85);
insert into picture (title, dimensions, author_idAuthor) values ('Man in the Middle', '601.3x284.5', 66);
insert into picture (title, dimensions, author_idAuthor) values ('Cheech & Chong''s Next Movie', '597.2x010.9', 29);
insert into picture (title, dimensions, author_idAuthor) values ('Voodoo Tiger', '526.0x156.9', 94);
insert into picture (title, dimensions, author_idAuthor) values ('Taming of the Shrew, The', '368.6x930.4', 71);
insert into picture (title, dimensions, author_idAuthor) values ('Jönssonligan & den svarta diamanten', '016.4x359.3', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Mr. Moto Takes a Chance', '779.2x200.8', 20);
insert into picture (title, dimensions, author_idAuthor) values ('From Russia with Love', '912.4x920.5', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Schmatta: Rags to Riches to Rags', '005.8x944.2', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Sallah', '527.7x571.0', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Lumihiutalemuodostelma', '980.8x695.7', 58);
insert into picture (title, dimensions, author_idAuthor) values ('Morning Patrol (Proini peripolos)', '003.4x525.0', 55);
insert into picture (title, dimensions, author_idAuthor) values ('Secret Things (Choses secrètes)', '093.2x459.9', 37);
insert into picture (title, dimensions, author_idAuthor) values ('Live Free or Die Hard', '389.8x066.1', 65);
insert into picture (title, dimensions, author_idAuthor) values ('Boy Meets Girl', '825.1x703.3', 18);
insert into picture (title, dimensions, author_idAuthor) values ('Missing, The', '558.8x630.7', 64);
insert into picture (title, dimensions, author_idAuthor) values ('You Will Be My Son (Tu seras mon fils)', '272.0x145.2', 22);
insert into picture (title, dimensions, author_idAuthor) values ('Guantanamera', '218.1x261.0', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Onegin', '019.6x591.6', 19);
insert into picture (title, dimensions, author_idAuthor) values ('Silent Sonata', '299.2x780.2', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Farewell (L''affaire Farewell)', '639.2x711.0', 28);
insert into picture (title, dimensions, author_idAuthor) values ('Spider', '930.9x895.1', 55);
insert into picture (title, dimensions, author_idAuthor) values ('Two Jakes, The', '172.7x421.6', 28);
insert into picture (title, dimensions, author_idAuthor) values ('Curiosity of Chance, The', '036.1x812.7', 78);
insert into picture (title, dimensions, author_idAuthor) values ('In the Army Now', '416.6x474.2', 40);
insert into picture (title, dimensions, author_idAuthor) values ('Where''s Marlowe?', '940.5x543.5', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Great World of Sound', '591.9x030.7', 79);
insert into picture (title, dimensions, author_idAuthor) values ('Tough and Deadly', '638.2x258.5', 46);
insert into picture (title, dimensions, author_idAuthor) values ('Loved Ones, The', '516.8x425.3', 21);
insert into picture (title, dimensions, author_idAuthor) values ('High and Dizzy', '340.8x975.2', 88);
insert into picture (title, dimensions, author_idAuthor) values ('My Mom''s New Boyfriend', '161.9x503.9', 71);
insert into picture (title, dimensions, author_idAuthor) values ('1', '594.7x800.4', 98);
insert into picture (title, dimensions, author_idAuthor) values ('Safe Passage', '386.5x192.5', 82);
insert into picture (title, dimensions, author_idAuthor) values ('NATO''s Secret Armies (Gladio: L''esercito segreto della Nato)', '985.8x371.9', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Gunday', '767.3x355.0', 47);
insert into picture (title, dimensions, author_idAuthor) values ('Thrust in Me', '263.1x269.4', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Demon Seed', '996.7x878.3', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Lupin the Third: The Secret of Mamo', '709.6x263.1', 79);
insert into picture (title, dimensions, author_idAuthor) values ('Johnny Apollo', '972.0x644.6', 42);
insert into picture (title, dimensions, author_idAuthor) values ('The Paris Express', '241.4x801.3', 89);
insert into picture (title, dimensions, author_idAuthor) values ('Beaver, The', '453.0x963.1', 52);
insert into picture (title, dimensions, author_idAuthor) values ('Grand Tour: Disaster in Time (Timescape)', '763.2x394.2', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Dead Snow 2: Red vs. Dead ', '155.6x183.5', 18);
insert into picture (title, dimensions, author_idAuthor) values ('Codebreaker', '740.5x196.8', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Three Brothers (Tre fratelli)', '177.4x318.6', 52);
insert into picture (title, dimensions, author_idAuthor) values ('One Magic Christmas', '625.9x667.0', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Deadly Voyage', '482.9x862.7', 44);
insert into picture (title, dimensions, author_idAuthor) values ('Ruins, The', '755.4x698.5', 11);
insert into picture (title, dimensions, author_idAuthor) values ('Lift, De', '139.5x770.6', 80);
insert into picture (title, dimensions, author_idAuthor) values ('Bundle of Joy', '130.7x245.7', 87);
insert into picture (title, dimensions, author_idAuthor) values ('Rebirth', '793.4x100.7', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Business of Being Born, The', '158.2x100.0', 95);
insert into picture (title, dimensions, author_idAuthor) values ('The Violent Kind', '196.1x126.1', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Monty Python Live (Mostly)', '215.1x001.5', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Aziz Ansari: Buried Alive', '373.3x237.5', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Toy Story 2', '290.4x099.7', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Challenge to Lassie', '853.2x180.2', 12);
insert into picture (title, dimensions, author_idAuthor) values ('Gumball Rally, The', '060.0x033.7', 57);
insert into picture (title, dimensions, author_idAuthor) values ('Wild Side', '861.7x296.8', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Brother''s War', '703.0x410.2', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Yes: 9012 Live', '612.4x124.6', 51);
insert into picture (title, dimensions, author_idAuthor) values ('Spider', '297.8x219.6', 48);
insert into picture (title, dimensions, author_idAuthor) values ('Toolbox Murders', '108.2x619.1', 65);
insert into picture (title, dimensions, author_idAuthor) values ('I Want Candy', '625.7x521.9', 76);
insert into picture (title, dimensions, author_idAuthor) values ('Lies (Gojitmal)', '326.8x173.4', 8);
insert into picture (title, dimensions, author_idAuthor) values ('Night in Casablanca, A', '956.7x315.9', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Bleeder', '693.4x579.5', 36);
insert into picture (title, dimensions, author_idAuthor) values ('War Witch (Rebelle)', '863.9x132.0', 75);
insert into picture (title, dimensions, author_idAuthor) values ('First Grader, The', '968.7x001.2', 91);
insert into picture (title, dimensions, author_idAuthor) values ('Beloved Berlin Wall (Liebe Mauer)', '536.4x284.2', 5);
insert into picture (title, dimensions, author_idAuthor) values ('Singing Marine, The', '941.0x590.5', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Strictly Sexual', '965.8x936.3', 43);
insert into picture (title, dimensions, author_idAuthor) values ('Adrift (Choi Voi)', '296.1x668.1', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Welcome to Woop-Woop', '824.0x236.0', 86);
insert into picture (title, dimensions, author_idAuthor) values ('Blink', '454.9x768.9', 22);
insert into picture (title, dimensions, author_idAuthor) values ('Brother Orchid', '320.1x843.2', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Misérables, Les', '448.7x895.8', 48);
insert into picture (title, dimensions, author_idAuthor) values ('Sterile Cuckoo, The', '328.5x878.6', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Farce of the Penguins', '411.1x498.5', 20);
insert into picture (title, dimensions, author_idAuthor) values ('Other Side of the Bed, The (Otro lado de la cama, El)', '650.4x334.1', 19);
insert into picture (title, dimensions, author_idAuthor) values ('Fire Within, The (Feu follet, Le)', '784.4x806.6', 95);
insert into picture (title, dimensions, author_idAuthor) values ('Chinese Coffee', '816.7x648.3', 81);
insert into picture (title, dimensions, author_idAuthor) values ('Ricky Gervais Live 4: Science', '015.0x312.7', 94);
insert into picture (title, dimensions, author_idAuthor) values ('Love Me If You Dare (Jeux d''enfants)', '460.5x569.0', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Anna Karenina', '007.1x103.9', 53);
insert into picture (title, dimensions, author_idAuthor) values ('Kill Your Darlings', '572.0x618.0', 97);
insert into picture (title, dimensions, author_idAuthor) values ('Reluctant Debutante, The', '339.1x500.1', 14);
insert into picture (title, dimensions, author_idAuthor) values ('Nobody', '607.7x479.4', 78);
insert into picture (title, dimensions, author_idAuthor) values ('Double Happiness', '196.6x493.7', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Fast and the Furious, The', '517.4x722.5', 2);
insert into picture (title, dimensions, author_idAuthor) values ('Confessions of a Burning Man', '553.2x574.6', 34);
insert into picture (title, dimensions, author_idAuthor) values ('Fraternity Demon', '863.1x967.1', 93);
insert into picture (title, dimensions, author_idAuthor) values ('Sometimes They Come Back... for More', '893.6x779.1', 48);
insert into picture (title, dimensions, author_idAuthor) values ('Paranormal Activity 2', '444.3x422.3', 92);
insert into picture (title, dimensions, author_idAuthor) values ('Ghost from the Machine (Phasma Ex Machina)', '990.9x669.1', 47);
insert into picture (title, dimensions, author_idAuthor) values ('Snow White', '897.2x961.7', 50);
insert into picture (title, dimensions, author_idAuthor) values ('Single White Female', '543.4x567.4', 6);
insert into picture (title, dimensions, author_idAuthor) values ('American Pimp', '693.2x069.9', 39);
insert into picture (title, dimensions, author_idAuthor) values ('Beastmaster 2: Through the Portal of Time', '535.6x917.7', 61);
insert into picture (title, dimensions, author_idAuthor) values ('Red''s Dream', '344.8x814.5', 84);
insert into picture (title, dimensions, author_idAuthor) values ('Crying Freeman', '622.8x577.7', 92);
insert into picture (title, dimensions, author_idAuthor) values ('McCullin', '939.5x120.7', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Bad Seed, The', '142.4x339.7', 41);
insert into picture (title, dimensions, author_idAuthor) values ('Punisher, The', '332.1x121.0', 26);
insert into picture (title, dimensions, author_idAuthor) values ('Toward the Unknown', '498.6x317.9', 26);
insert into picture (title, dimensions, author_idAuthor) values ('Adult World', '339.3x746.4', 9);
insert into picture (title, dimensions, author_idAuthor) values ('Godzilla and Mothra: The Battle for Earth (Gojira vs. Mosura)', '710.8x807.8', 11);
insert into picture (title, dimensions, author_idAuthor) values ('Waiting for Guffman', '441.3x476.6', 73);
insert into picture (title, dimensions, author_idAuthor) values ('Back Door to Hell', '534.8x516.3', 29);
insert into picture (title, dimensions, author_idAuthor) values ('Ain''t in It for My Health: A Film About Levon Helm', '986.5x911.1', 74);
insert into picture (title, dimensions, author_idAuthor) values ('Jonestown: The Life and Death of Peoples Temple', '244.3x653.7', 96);
insert into picture (title, dimensions, author_idAuthor) values ('Americano', '023.7x676.5', 23);
insert into picture (title, dimensions, author_idAuthor) values ('Les invincibles', '398.3x604.5', 82);
insert into picture (title, dimensions, author_idAuthor) values ('Stones in Exile', '634.7x822.5', 35);
insert into picture (title, dimensions, author_idAuthor) values ('Land of Silence and Darkness (Land des Schweigens und der Dunkelheit)', '488.0x397.7', 32);
insert into picture (title, dimensions, author_idAuthor) values ('Finder''s Fee', '397.1x073.8', 38);
insert into picture (title, dimensions, author_idAuthor) values ('Resident Evil: Apocalypse', '007.8x608.4', 37);
insert into picture (title, dimensions, author_idAuthor) values ('Thunder Soul', '296.7x267.6', 30);
insert into picture (title, dimensions, author_idAuthor) values ('Forgotten', '753.4x105.0', 23);
