insert into Plane (capacity, code, model) values (250, 'Chevrolet', 'Sportvan G30');
insert into Plane (capacity, code, model) values (120, 'Ford', 'Freestyle');
insert into Plane (capacity, code, model) values (120, 'Buick', 'Riviera');
insert into Plane (capacity, code, model) values (50, 'Lexus', 'RX');
insert into Plane (capacity, code, model) values (120, 'Toyota', 'Camry Hybrid');
insert into Plane (capacity, code, model) values (250, 'Dodge', 'Ram 2500');
insert into Plane (capacity, code, model) values (50, 'Lexus', 'LS Hybrid');
insert into Plane (capacity, code, model) values (300, 'Land Rover', 'Discovery');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', 'E-Class');
insert into Plane (capacity, code, model) values (120, 'Ford', 'Econoline E250');
insert into Plane (capacity, code, model) values (250, 'Subaru', 'Justy');
insert into Plane (capacity, code, model) values (250, 'Acura', 'TL');
insert into Plane (capacity, code, model) values (60, 'Ford', 'F-350 Super Duty');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', 'G-Class');
insert into Plane (capacity, code, model) values (120, 'Volvo', 'S80');
insert into Plane (capacity, code, model) values (120, 'Acura', 'TSX');
insert into Plane (capacity, code, model) values (60, 'Alfa Romeo', '164');
insert into Plane (capacity, code, model) values (300, 'Chevrolet', 'Blazer');
insert into Plane (capacity, code, model) values (250, 'GMC', 'Savana 1500');
insert into Plane (capacity, code, model) values (120, 'Toyota', 'Corolla');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Aveo');
insert into Plane (capacity, code, model) values (120, 'Toyota', 'Sequoia');
insert into Plane (capacity, code, model) values (50, 'Ford', 'E-Series');
insert into Plane (capacity, code, model) values (120, 'Dodge', 'Ram Van B150');
insert into Plane (capacity, code, model) values (120, 'Dodge', 'Ram 2500');
insert into Plane (capacity, code, model) values (60, 'Plymouth', 'Colt Vista');
insert into Plane (capacity, code, model) values (60, 'Lexus', 'ES');
insert into Plane (capacity, code, model) values (300, 'Mitsubishi', 'GTO');
insert into Plane (capacity, code, model) values (300, 'Lexus', 'CT');
insert into Plane (capacity, code, model) values (250, 'Chevrolet', 'Express 3500');
insert into Plane (capacity, code, model) values (300, 'GMC', '1500 Club Coupe');
insert into Plane (capacity, code, model) values (300, 'Chevrolet', 'Express 1500');
insert into Plane (capacity, code, model) values (60, 'Pontiac', 'Safari');
insert into Plane (capacity, code, model) values (250, 'Chrysler', 'Imperial');
insert into Plane (capacity, code, model) values (50, 'GMC', 'Savana 3500');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'LeMans');
insert into Plane (capacity, code, model) values (120, 'Nissan', '350Z Roadster');
insert into Plane (capacity, code, model) values (120, 'Acura', 'NSX');
insert into Plane (capacity, code, model) values (300, 'Chevrolet', 'Suburban 1500');
insert into Plane (capacity, code, model) values (250, 'Hyundai', 'Sonata');
insert into Plane (capacity, code, model) values (60, 'BMW', '330');
insert into Plane (capacity, code, model) values (60, 'Lexus', 'ES');
insert into Plane (capacity, code, model) values (250, 'Lexus', 'RX');
insert into Plane (capacity, code, model) values (50, 'Scion', 'tC');
insert into Plane (capacity, code, model) values (300, 'Oldsmobile', 'Bravada');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', 'C-Class');
insert into Plane (capacity, code, model) values (300, 'GMC', 'Sierra');
insert into Plane (capacity, code, model) values (250, 'Bentley', 'Continental');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'CLK-Class');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Corvette');
insert into Plane (capacity, code, model) values (50, 'BMW', 'X5');
insert into Plane (capacity, code, model) values (120, 'Mitsubishi', 'Eclipse');
insert into Plane (capacity, code, model) values (50, 'Mazda', '626');
insert into Plane (capacity, code, model) values (50, 'Cadillac', 'Seville');
insert into Plane (capacity, code, model) values (120, 'Kia', 'Optima');
insert into Plane (capacity, code, model) values (50, 'Nissan', 'Sentra');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', 'SL-Class');
insert into Plane (capacity, code, model) values (250, 'Chrysler', 'Sebring');
insert into Plane (capacity, code, model) values (120, 'Buick', 'LeSabre');
insert into Plane (capacity, code, model) values (250, 'Acura', 'RL');
insert into Plane (capacity, code, model) values (120, 'Chevrolet', 'Uplander');
insert into Plane (capacity, code, model) values (60, 'Cadillac', 'XLR');
insert into Plane (capacity, code, model) values (250, 'Saturn', 'Aura');
insert into Plane (capacity, code, model) values (250, 'Jeep', 'Grand Cherokee');
insert into Plane (capacity, code, model) values (50, 'Audi', '100');
insert into Plane (capacity, code, model) values (300, 'Infiniti', 'IPL G');
insert into Plane (capacity, code, model) values (50, 'Saab', '900');
insert into Plane (capacity, code, model) values (50, 'Mazda', 'Mazdaspeed 3');
insert into Plane (capacity, code, model) values (50, 'Buick', 'Century');
insert into Plane (capacity, code, model) values (120, 'GMC', '2500 Club Coupe');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Grand Prix');
insert into Plane (capacity, code, model) values (300, 'Dodge', 'Charger');
insert into Plane (capacity, code, model) values (50, 'Ford', 'Escape');
insert into Plane (capacity, code, model) values (50, 'Land Rover', 'Discovery');
insert into Plane (capacity, code, model) values (60, 'Smart', 'Fortwo');
insert into Plane (capacity, code, model) values (250, 'Dodge', 'Ram 1500');
insert into Plane (capacity, code, model) values (250, 'Rolls-Royce', 'Phantom');
insert into Plane (capacity, code, model) values (60, 'Toyota', 'Highlander');
insert into Plane (capacity, code, model) values (120, 'Ferrari', 'FF');
insert into Plane (capacity, code, model) values (60, 'Honda', 'CR-V');
insert into Plane (capacity, code, model) values (120, 'Honda', 'Element');
insert into Plane (capacity, code, model) values (50, 'Honda', 'CR-V');
insert into Plane (capacity, code, model) values (50, 'Acura', 'TL');
insert into Plane (capacity, code, model) values (120, 'Buick', 'Riviera');
insert into Plane (capacity, code, model) values (250, 'Jeep', 'Cherokee');
insert into Plane (capacity, code, model) values (250, 'Chevrolet', 'Silverado 3500');
insert into Plane (capacity, code, model) values (250, 'Nissan', 'Frontier');
insert into Plane (capacity, code, model) values (120, 'GMC', 'Sonoma');
insert into Plane (capacity, code, model) values (50, 'Mercury', 'Mountaineer');
insert into Plane (capacity, code, model) values (120, 'Hyundai', 'Elantra');
insert into Plane (capacity, code, model) values (250, 'Ford', 'Escort');
insert into Plane (capacity, code, model) values (300, 'Lotus', 'Evora');
insert into Plane (capacity, code, model) values (250, 'GMC', 'Canyon');
insert into Plane (capacity, code, model) values (120, 'Ford', 'Crown Victoria');
insert into Plane (capacity, code, model) values (50, 'BMW', 'M6');
insert into Plane (capacity, code, model) values (50, 'Volvo', 'C70');
insert into Plane (capacity, code, model) values (60, 'BMW', '3 Series');
insert into Plane (capacity, code, model) values (120, 'Maserati', 'GranTurismo');
insert into Plane (capacity, code, model) values (300, 'Ford', 'Thunderbird');
insert into Plane (capacity, code, model) values (120, 'Geo', 'Metro');
insert into Plane (capacity, code, model) values (60, 'Pontiac', 'Grand Prix');
insert into Plane (capacity, code, model) values (250, 'Toyota', 'Prius');
insert into Plane (capacity, code, model) values (60, 'Honda', 'Pilot');
insert into Plane (capacity, code, model) values (120, 'Chevrolet', 'Corvette');
insert into Plane (capacity, code, model) values (250, 'Lincoln', 'Mark VIII');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Tempest');
insert into Plane (capacity, code, model) values (300, 'Ford', 'Country');
insert into Plane (capacity, code, model) values (50, 'GMC', '2500');
insert into Plane (capacity, code, model) values (300, 'Pontiac', 'Firefly');
insert into Plane (capacity, code, model) values (250, 'Chevrolet', 'Express 2500');
insert into Plane (capacity, code, model) values (60, 'Isuzu', 'Ascender');
insert into Plane (capacity, code, model) values (50, 'Mitsubishi', 'Cordia');
insert into Plane (capacity, code, model) values (50, 'Pontiac', 'Tempest');
insert into Plane (capacity, code, model) values (250, 'Ford', 'Econoline E350');
insert into Plane (capacity, code, model) values (300, 'Acura', 'SLX');
insert into Plane (capacity, code, model) values (60, 'Alfa Romeo', '164');
insert into Plane (capacity, code, model) values (50, 'Saab', '9-3');
insert into Plane (capacity, code, model) values (300, 'Kia', 'Carens');
insert into Plane (capacity, code, model) values (250, 'Volvo', 'V40');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'CLK-Class');
insert into Plane (capacity, code, model) values (120, 'Cadillac', 'STS-V');
insert into Plane (capacity, code, model) values (50, 'Mercury', 'Monterey');
insert into Plane (capacity, code, model) values (50, 'Subaru', 'Outback');
insert into Plane (capacity, code, model) values (120, 'Volvo', 'C30');
insert into Plane (capacity, code, model) values (50, 'Ford', 'Thunderbird');
insert into Plane (capacity, code, model) values (50, 'Nissan', 'NV1500');
insert into Plane (capacity, code, model) values (250, 'Chrysler', 'New Yorker');
insert into Plane (capacity, code, model) values (250, 'Buick', 'Century');
insert into Plane (capacity, code, model) values (250, 'Subaru', 'Outback');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Camaro');
insert into Plane (capacity, code, model) values (50, 'Toyota', 'T100');
insert into Plane (capacity, code, model) values (60, 'BMW', 'X5');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Avalanche');
insert into Plane (capacity, code, model) values (120, 'Chevrolet', 'Lumina');
insert into Plane (capacity, code, model) values (120, 'Subaru', 'Justy');
insert into Plane (capacity, code, model) values (120, 'Mitsubishi', 'Montero');
insert into Plane (capacity, code, model) values (300, 'Rolls-Royce', 'Ghost');
insert into Plane (capacity, code, model) values (250, 'Aston Martin', 'V12 Vantage');
insert into Plane (capacity, code, model) values (300, 'Nissan', 'Maxima');
insert into Plane (capacity, code, model) values (250, 'Plymouth', 'Grand Voyager');
insert into Plane (capacity, code, model) values (300, 'Mitsubishi', 'Raider');
insert into Plane (capacity, code, model) values (300, 'Honda', 'Element');
insert into Plane (capacity, code, model) values (60, 'Chevrolet', 'Silverado');
insert into Plane (capacity, code, model) values (120, 'Saab', '9-3');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'W126');
insert into Plane (capacity, code, model) values (250, 'Toyota', 'Avalon');
insert into Plane (capacity, code, model) values (250, 'Oldsmobile', '98');
insert into Plane (capacity, code, model) values (300, 'Buick', 'Regal');
insert into Plane (capacity, code, model) values (300, 'MINI', 'Clubman');
insert into Plane (capacity, code, model) values (300, 'Buick', 'Riviera');
insert into Plane (capacity, code, model) values (250, 'Ford', 'Contour');
insert into Plane (capacity, code, model) values (60, 'Bugatti', 'Veyron');
insert into Plane (capacity, code, model) values (120, 'Chevrolet', 'SSR');
insert into Plane (capacity, code, model) values (120, 'Buick', 'Riviera');
insert into Plane (capacity, code, model) values (120, 'Maserati', 'Quattroporte');
insert into Plane (capacity, code, model) values (300, 'Ford', 'Ranger');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'G-Class');
insert into Plane (capacity, code, model) values (60, 'Mercedes-Benz', 'M-Class');
insert into Plane (capacity, code, model) values (60, 'Jaguar', 'XJ');
insert into Plane (capacity, code, model) values (250, 'Ford', 'ZX2');
insert into Plane (capacity, code, model) values (250, 'Mercury', 'Capri');
insert into Plane (capacity, code, model) values (250, 'Toyota', 'Previa');
insert into Plane (capacity, code, model) values (60, 'Honda', 'Accord');
insert into Plane (capacity, code, model) values (250, 'Mazda', 'RX-8');
insert into Plane (capacity, code, model) values (300, 'BMW', 'M5');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Silverado 1500');
insert into Plane (capacity, code, model) values (300, 'Honda', 'Civic');
insert into Plane (capacity, code, model) values (60, 'Cadillac', 'Eldorado');
insert into Plane (capacity, code, model) values (250, 'Volvo', 'S60');
insert into Plane (capacity, code, model) values (60, 'Lotus', 'Exige');
insert into Plane (capacity, code, model) values (60, 'Volkswagen', 'Jetta');
insert into Plane (capacity, code, model) values (50, 'Infiniti', 'Q');
insert into Plane (capacity, code, model) values (60, 'Acura', 'Legend');
insert into Plane (capacity, code, model) values (50, 'Suzuki', 'Swift');
insert into Plane (capacity, code, model) values (120, 'Acura', 'TSX');
insert into Plane (capacity, code, model) values (300, 'Oldsmobile', 'Cutlass Supreme');
insert into Plane (capacity, code, model) values (300, 'Audi', 'RS6');
insert into Plane (capacity, code, model) values (250, 'Toyota', 'Land Cruiser');
insert into Plane (capacity, code, model) values (120, 'Subaru', 'Justy');
insert into Plane (capacity, code, model) values (60, 'GMC', 'Yukon XL 1500');
insert into Plane (capacity, code, model) values (120, 'Toyota', 'Previa');
insert into Plane (capacity, code, model) values (60, 'Suzuki', 'Equator');
insert into Plane (capacity, code, model) values (300, 'Aston Martin', 'V12 Vantage');
insert into Plane (capacity, code, model) values (50, 'Dodge', 'Charger');
insert into Plane (capacity, code, model) values (250, 'Suzuki', 'Sidekick');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Silverado 2500');
insert into Plane (capacity, code, model) values (300, 'Kia', 'Amanti');
insert into Plane (capacity, code, model) values (120, 'Lexus', 'SC');
insert into Plane (capacity, code, model) values (50, 'Ford', 'Aerostar');
insert into Plane (capacity, code, model) values (60, 'Volvo', 'XC70');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Firebird');
insert into Plane (capacity, code, model) values (60, 'Toyota', 'Xtra');
insert into Plane (capacity, code, model) values (300, 'Volkswagen', 'Jetta');
insert into Plane (capacity, code, model) values (120, 'BMW', '650');
insert into Plane (capacity, code, model) values (300, 'Mercury', 'Mountaineer');
insert into Plane (capacity, code, model) values (120, 'Mitsubishi', 'Galant');
insert into Plane (capacity, code, model) values (250, 'Audi', 'Q5');
insert into Plane (capacity, code, model) values (60, 'Audi', 'A4');
insert into Plane (capacity, code, model) values (60, 'Chevrolet', 'Express 2500');
insert into Plane (capacity, code, model) values (120, 'Kia', 'Sedona');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'G-Class');
insert into Plane (capacity, code, model) values (250, 'Toyota', 'Matrix');
insert into Plane (capacity, code, model) values (250, 'BMW', '530');
insert into Plane (capacity, code, model) values (250, 'Mercedes-Benz', '300SL');
insert into Plane (capacity, code, model) values (300, 'Mitsubishi', 'Mighty Max');
insert into Plane (capacity, code, model) values (300, 'Lotus', 'Exige');
insert into Plane (capacity, code, model) values (120, 'Lexus', 'IS');
insert into Plane (capacity, code, model) values (60, 'Ford', 'Escape');
insert into Plane (capacity, code, model) values (250, 'Oldsmobile', 'Silhouette');
insert into Plane (capacity, code, model) values (250, 'Saturn', 'S-Series');
insert into Plane (capacity, code, model) values (60, 'Porsche', 'Boxster');
insert into Plane (capacity, code, model) values (300, 'GMC', '1500 Club Coupe');
insert into Plane (capacity, code, model) values (300, 'Chrysler', '300');
insert into Plane (capacity, code, model) values (120, 'Volkswagen', 'GTI');
insert into Plane (capacity, code, model) values (120, 'Fillmore', 'Fillmore');
insert into Plane (capacity, code, model) values (60, 'Oldsmobile', '98');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Firebird');
insert into Plane (capacity, code, model) values (300, 'Honda', 'CR-V');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Bonneville');
insert into Plane (capacity, code, model) values (250, 'Buick', 'Century');
insert into Plane (capacity, code, model) values (120, 'Pontiac', 'Grand Prix');
insert into Plane (capacity, code, model) values (60, 'GMC', 'Sonoma');
insert into Plane (capacity, code, model) values (300, 'Audi', 'Cabriolet');
insert into Plane (capacity, code, model) values (60, 'Buick', 'Riviera');
insert into Plane (capacity, code, model) values (250, 'Mitsubishi', 'Mighty Max');
insert into Plane (capacity, code, model) values (120, 'Porsche', 'Cayman');
insert into Plane (capacity, code, model) values (60, 'Nissan', '350Z');
insert into Plane (capacity, code, model) values (60, 'Lotus', 'Elan');
insert into Plane (capacity, code, model) values (120, 'Jeep', 'Wrangler');
insert into Plane (capacity, code, model) values (50, 'Chevrolet', 'Suburban 1500');
insert into Plane (capacity, code, model) values (250, 'Ford', 'E-Series');
insert into Plane (capacity, code, model) values (50, 'Nissan', 'Sentra');
insert into Plane (capacity, code, model) values (300, 'Ford', 'Escort');
insert into Plane (capacity, code, model) values (250, 'Volkswagen', 'Golf');
insert into Plane (capacity, code, model) values (250, 'Mercedes-Benz', 'M-Class');
insert into Plane (capacity, code, model) values (120, 'Mazda', 'B-Series');
insert into Plane (capacity, code, model) values (60, 'Dodge', 'Stratus');
insert into Plane (capacity, code, model) values (250, 'Lotus', 'Exige');
insert into Plane (capacity, code, model) values (300, 'Ford', 'Fiesta');
insert into Plane (capacity, code, model) values (120, 'Suzuki', 'SX4');
insert into Plane (capacity, code, model) values (50, 'Toyota', '4Runner');
insert into Plane (capacity, code, model) values (120, 'Mercury', 'Monterey');
insert into Plane (capacity, code, model) values (50, 'Dodge', 'Grand Caravan');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'W201');
insert into Plane (capacity, code, model) values (120, 'Lexus', 'GX');
insert into Plane (capacity, code, model) values (50, 'Kia', 'Rondo');
insert into Plane (capacity, code, model) values (250, 'Pontiac', 'Grand Prix');
insert into Plane (capacity, code, model) values (60, 'BMW', 'M5');
insert into Plane (capacity, code, model) values (300, 'Dodge', 'Dakota');
insert into Plane (capacity, code, model) values (60, 'Chrysler', 'Voyager');
insert into Plane (capacity, code, model) values (50, 'Dodge', 'Ram Wagon B250');
insert into Plane (capacity, code, model) values (300, 'Mitsubishi', 'Pajero');
insert into Plane (capacity, code, model) values (300, 'GMC', '1500 Club Coupe');
insert into Plane (capacity, code, model) values (300, 'Chevrolet', 'Sportvan G20');
insert into Plane (capacity, code, model) values (300, 'Mercury', 'Mystique');
insert into Plane (capacity, code, model) values (250, 'Volvo', 'XC60');
insert into Plane (capacity, code, model) values (300, 'Hummer', 'H2');
insert into Plane (capacity, code, model) values (60, 'Toyota', 'Supra');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', 'SLK-Class');
insert into Plane (capacity, code, model) values (60, 'Subaru', 'Impreza');
insert into Plane (capacity, code, model) values (120, 'Suzuki', 'Grand Vitara');
insert into Plane (capacity, code, model) values (300, 'Pontiac', 'Firefly');
insert into Plane (capacity, code, model) values (60, 'Buick', 'Verano');
insert into Plane (capacity, code, model) values (60, 'Lexus', 'LX');
insert into Plane (capacity, code, model) values (250, 'Nissan', 'Altima');
insert into Plane (capacity, code, model) values (120, 'Mercedes-Benz', 'Sprinter');
insert into Plane (capacity, code, model) values (60, 'Dodge', 'Ram');
insert into Plane (capacity, code, model) values (50, 'Mercedes-Benz', '300SL');
insert into Plane (capacity, code, model) values (60, 'Hyundai', 'Tiburon');
insert into Plane (capacity, code, model) values (120, 'Hyundai', 'XG350');
insert into Plane (capacity, code, model) values (120, 'Acura', 'Vigor');
insert into Plane (capacity, code, model) values (60, 'Chevrolet', 'Camaro');
insert into Plane (capacity, code, model) values (60, 'Peugeot', '207');
insert into Plane (capacity, code, model) values (250, 'Kia', 'Mentor');
insert into Plane (capacity, code, model) values (120, 'Infiniti', 'G37');
insert into Plane (capacity, code, model) values (120, 'Chevrolet', 'Malibu Maxx');
insert into Plane (capacity, code, model) values (120, 'Oldsmobile', 'Aurora');
insert into Plane (capacity, code, model) values (60, 'Audi', 'A4');
insert into Plane (capacity, code, model) values (60, 'GMC', 'Savana 3500');
insert into Plane (capacity, code, model) values (300, 'Volvo', 'S80');
insert into Plane (capacity, code, model) values (250, 'Land Rover', 'Discovery');
insert into Plane (capacity, code, model) values (300, 'Chrysler', 'Crossfire');
insert into Plane (capacity, code, model) values (250, 'Acura', 'Integra');
insert into Plane (capacity, code, model) values (60, 'Audi', 'A6');
insert into Plane (capacity, code, model) values (250, 'Volkswagen', 'GTI');
insert into Plane (capacity, code, model) values (120, 'Volkswagen', 'Eurovan');
insert into Plane (capacity, code, model) values (300, 'GMC', 'Vandura 1500');
insert into Plane (capacity, code, model) values (60, 'Volkswagen', 'Type 2');
insert into Plane (capacity, code, model) values (60, 'Subaru', 'Loyale');
insert into Plane (capacity, code, model) values (50, 'Nissan', 'Murano');
insert into Plane (capacity, code, model) values (120, 'GMC', 'Savana 3500');
insert into Plane (capacity, code, model) values (60, 'Honda', 'Prelude');
insert into Plane (capacity, code, model) values (250, 'Ford', 'Crown Victoria');
insert into Plane (capacity, code, model) values (50, 'Mitsubishi', 'Diamante');
insert into Plane (capacity, code, model) values (50, 'Hyundai', 'Excel');
insert into Plane (capacity, code, model) values (250, 'Audi', '5000S');
insert into Plane (capacity, code, model) values (50, 'Porsche', '928');
insert into Plane (capacity, code, model) values (250, 'Volvo', 'V50');
insert into Plane (capacity, code, model) values (60, 'Volkswagen', 'Golf');
insert into Plane (capacity, code, model) values (50, 'Isuzu', 'Ascender');
